# Change these first
owner: synthropai # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Synthrop AI
    url: https://synthrop.ai
 
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: System Status
  introTitle: "**Synthrop.AI** - Clarity Through Intelligence."
  introMessage: Synthrop.AI transforms corporate complexity into clarity and speed through intelligent AI agents that orchestrate data, decisions, and operations.
  navbar:
    - title: Synthrop AI
      href: https://synthrop.ai
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
